name: 'Install Minimina'
description: 'Installs the minimina package from a specified stream or from a specific commit or branch.'
inputs:
  stream:
    description: 'Stream for the package - can be stable or unstable.'
    required: true
    default: 'stable'
  commit_or_branch:
    description: 'Specific commit hash or branch name to clone and build from source.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install from package
      if: inputs.commit_or_branch == ''
      run: |
        echo "deb [trusted=yes] http://packages.o1test.net ubuntu ${{ inputs.stream }}" | sudo tee /etc/apt/sources.list.d/mina.list
        sudo apt-get update
        sudo apt-get install -y minimina
        mkdir -p minimina_home
        echo "MINIMINA_HOME=$(pwd)/minimina_home" >> $GITHUB_ENV
      shell: bash

    - name: Install and build from source
      if: inputs.commit_or_branch != ''
      run: |
        git clone https://github.com/MinaFoundation/minimina.git
        cd minimina
        git checkout ${{ inputs.commit_or_branch }}
        cargo build
        sudo cp target/debug/minimina /usr/local/bin/minimina
        mkdir -p minimina_home
        echo "MINIMINA_HOME=$(pwd)/minimina_home" >> $GITHUB_ENV
        cd -
      shell: bash
